name: Generate Changelog, bump version and publish
on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest
    if: !contains(github.event.head_commit.author.name, 'YDB Platform But')
    steps:
      - run: echo ${{ github.event.head_commit.author.name }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
          token: ${{ secrets.BOT_TOKEN }}
      - run: |
          git config --global user.email "ydb-platform@yandex-team.ru"
          git config --global user.name "YDB Platform Bot"
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run release
      - run: git push --follow-tags origin master
